[[NCCL]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "e84836398a0755c80ee3ad93028850d39a7543f5"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "7d83682839a44e45a3e1b15535c35419169efa5c380426be4a43cdb4e8e87231"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "jetson"
git-tree-sha1 = "4535692101a7b1494e13b861d231cdecbffe07e7"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "297d41c2c244019b630f26018cf264959c993bcd818ab901b5219e44646a633a"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.0.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "sbsa"
git-tree-sha1 = "733df26d66274e23a77b34ba05928826ea91743d"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "5f4144f8baf2911174c71784b5827b3257992693ac4bddf7005685ddd636f71c"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.0.tar.gz"
[[NCCL]]
arch = "x86_64"
cuda = "12.1"
git-tree-sha1 = "c789935e7cb8047de87d7226d404d3db55f43acd"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "e711a235edf6ddbf9060f387530040e771440bcd59b8571bdedca2f2e38f8b4a"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.x86_64-linux-gnu-cuda+12.1.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.1"
cuda_platform = "jetson"
git-tree-sha1 = "9d16a30608a8032f5832eac3a869f0da6a2888ae"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "c827cb1ccfa005d067890c2d45e5eac8e4e4876479c1d2b6a61315af032b374c"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.1.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.1"
cuda_platform = "sbsa"
git-tree-sha1 = "fedd95699f95e5de29f688845008d6752e21da76"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "e745e2b5f0a91aa11c5f72e6c768e4b4538666dd2063d614277ef4387f28c081"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.1.tar.gz"
[[NCCL]]
arch = "x86_64"
cuda = "12.2"
git-tree-sha1 = "e64b22794f9d638e037168c55585b4f8f804f14e"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "3bd4fa10b81b96fe2f1b15a36137b5ae5959c83a9e50467014571f4249a57bab"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.x86_64-linux-gnu-cuda+12.2.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.2"
cuda_platform = "jetson"
git-tree-sha1 = "ba78c0686d63616fcbf62633272ba073112fc327"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "bd6097650e922738b1d0c96aedfc61f90da4537eb991f2dd30fbc2ed622c0d4c"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.2.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.2"
cuda_platform = "sbsa"
git-tree-sha1 = "36c1addf27cb98a9d6a938162080bb40cee199f4"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "dcf6f120ae33a0c7ab6e19657579420e7f29d9fb1ef3af368e7ba22908c62a77"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.2.tar.gz"
[[NCCL]]
arch = "x86_64"
cuda = "12.3"
git-tree-sha1 = "b60e41e2a8fb34e1714023733322d97db3aceb9f"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "0462aff886e081eb53258d9aa2578fc51acf1829cd2e5e25fc401325e3c50c83"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.x86_64-linux-gnu-cuda+12.3.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.3"
cuda_platform = "sbsa"
git-tree-sha1 = "7e9ba5b564e759ee21ce783ff272014e75487ce7"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "44e9f15be0cabda5eb9d3da2246be3abb132be8e087552fec4b96d505a4e9e9c"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.3.tar.gz"
[[NCCL]]
arch = "x86_64"
cuda = "12.4"
git-tree-sha1 = "12f4e39afcd84a08b7da0a7ce2759c3b275e2b0f"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "1c631a84a1521a8103b17300c60cd3afa34cf60ce78076c8788acca3e519066a"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.x86_64-linux-gnu-cuda+12.4.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.4"
cuda_platform = "jetson"
git-tree-sha1 = "dc149cfdf5e2c97c62d3106ece2ed3fe9c8d2b2d"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "0afbc959bd63aa6dfd88c7f0c0875f32cec3cabcacc89a6ecb74262d890e25b9"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.4.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.4"
cuda_platform = "sbsa"
git-tree-sha1 = "2d9a254508a05ab9ba0b35cc38ee9f6789f80d02"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "9b9c3ad2ffdb6e36efd080dab5403ce9c5a0c31d1f5bd495c6d13ad06178eb20"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.4.tar.gz"
[[NCCL]]
arch = "x86_64"
cuda = "12.5"
git-tree-sha1 = "c003554b7089606d20c2b8ba18eda7ccae9388ee"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "3b468b520ce231b24f9cd1422ee420a82ac4406bbb079fd8f58c75972f3ed003"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.x86_64-linux-gnu-cuda+12.5.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.5"
cuda_platform = "jetson"
git-tree-sha1 = "c21a24039a2728cb7d3a8098887d712f5427f6f4"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "96bfb491d52a56d814afbb6e6134aeaeefad9608fbfaea816034385bbb525a76"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.5.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.5"
cuda_platform = "sbsa"
git-tree-sha1 = "e5cecdeec230e7e92a7e11257e2f33ceaae4999c"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "0a2bdcfd428abbe33d694f8dbea3364f71a889219da9c0928b96bcbfeab6e297"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.5.tar.gz"
[[NCCL]]
arch = "x86_64"
cuda = "12.6"
git-tree-sha1 = "3fefaca6e2aa74a898caf30f8bb78a99a5b32a16"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "04bd2d83e39a3ea539fe3433656a4c92306f90c3452a379f437a121c9126deaf"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.x86_64-linux-gnu-cuda+12.6.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.6"
cuda_platform = "jetson"
git-tree-sha1 = "330c91a9ee563d2864bcde68b6d2940792e7d69d"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "955026c4922a56c472d5c516cfab4638d2c8b44187774da328eb334b73375e47"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.6.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.6"
cuda_platform = "sbsa"
git-tree-sha1 = "d16cd993a393f64a08f7f0e864efd8f270195e5a"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "e159660c35d6b8e8d8516fac9e84703a8847625c3f08e304311b914bc2e849fb"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.6.tar.gz"
[[NCCL]]
arch = "x86_64"
cuda = "12.8"
git-tree-sha1 = "1ce9ed15087a03db3cd641d579781c75093f9b73"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "c3f64ce228dd65fe401c9e24470d9bfc447f1208ade7b235f2c3c971fc2c77a2"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.x86_64-linux-gnu-cuda+12.8.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.8"
cuda_platform = "jetson"
git-tree-sha1 = "3d1215e22ec425e97183074a2314f7e3f72fa758"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "4647710fb69b0a5a5c1d12d91278f4c6a6c97a8d5dbde82cb53120b173cddd43"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.8.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.8"
cuda_platform = "sbsa"
git-tree-sha1 = "1c16d14419178da706e20cdf18a89fe733d0654d"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "c5da166a875648edaac4cb822aaca1e037ce1e16c6e72330a188f18bf9074a81"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.8.tar.gz"
[[NCCL]]
arch = "x86_64"
cuda = "12.9"
git-tree-sha1 = "b40757c32104349052a13ecfaa1b92b630d5dd62"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "7e556176010a5d4a2d1ca7c1dc6aab151dcc0f64903616de6922e85aaf5bef1b"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.x86_64-linux-gnu-cuda+12.9.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.9"
cuda_platform = "jetson"
git-tree-sha1 = "b442525115d810f2e6607fcd7e3c2722fe9c2998"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "0758dd9854f6187f778939629e07370993e2387484f2df0136b821b23b6e2c66"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.9.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.9"
cuda_platform = "sbsa"
git-tree-sha1 = "ee924cc390646d6e65f622b650ed2f0472eb09b7"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "f4742a28d1435835a453f078e7b85f5e42d525160dd67439560f408dcc9ab455"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.9.tar.gz"
[[NCCL]]
arch = "x86_64"
cuda = "13.0"
git-tree-sha1 = "7d0f293c8ece23034a3a882ec38209dbd9d412e3"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "100402288a37827724a2f77869450a00ac7b8f18b08b7c14e8161d0cc6f7769b"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.x86_64-linux-gnu-cuda+13.0.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "13.0"
git-tree-sha1 = "b35d4a6a7b9f5154c7504193862af53ea50ea9ec"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "0953435f745d6c78a67d54fd6714dc5baef61151273e4f497a68e0d55a9e3bdd"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.30.7+0/NCCL.v2.30.7.aarch64-linux-gnu-cuda+13.0.tar.gz"
