[[NCCL]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "e53fe7f07d28ca5c3796ca913e2ac358d750367d"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "0fc3bffd9e411201e7574f2f922468d996cd57d72a6fd8df0a32a6c5f3c034dd"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "jetson"
git-tree-sha1 = "09dfa42a34c43b068c77a77fefbac137c3d9914f"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "8153806d5e51f68b83b59f5e47fb44acaed514e56c8286c99d11be616619d28c"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.0.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "sbsa"
git-tree-sha1 = "c5e1d6f0c46a8c0173902262cf4b8cd4bcec7b27"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "0f071b9ce88e7320a6528403cc0881953bd170c62a70f6b0f4dee33b06071352"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.0.tar.gz"
[[NCCL]]
arch = "x86_64"
cuda = "12.1"
git-tree-sha1 = "2317da9018a8201e0b8eb3535cd3b3e7ba5dc5d6"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "16c73bc1e34bbbf8426caf1a8b223cf243f80fe1abcb3d0071cef54053fcfef3"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.x86_64-linux-gnu-cuda+12.1.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.1"
cuda_platform = "jetson"
git-tree-sha1 = "a21fdb4a1a46adb870e50c9d89305ab2a8660040"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "8f8cbf5ca6b0ace1623331a18928c79e457305d1f29ad5dc12562bff5256303f"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.1.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.1"
cuda_platform = "sbsa"
git-tree-sha1 = "866a29b879c777846de02a62c4fd55278aa61ccd"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "a398c8089a4e9b2e1581fa68ebd85d8fe206918402554c52237c5d4871815f30"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.1.tar.gz"
[[NCCL]]
arch = "x86_64"
cuda = "12.2"
git-tree-sha1 = "79d78607689a767b0ae0c15ddc7f62d039126675"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "b41b45a1db88474f079ed48e33b839b374917ac17c46a2dd78862370ddf90d55"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.x86_64-linux-gnu-cuda+12.2.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.2"
cuda_platform = "jetson"
git-tree-sha1 = "64ce3858f8202afc4a61adb46d51139e398238f0"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "c1646def59986b8ec7b0f51865e58e9ba01bfe4e655592b74efd2d750830c563"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.2.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.2"
cuda_platform = "sbsa"
git-tree-sha1 = "062c196538ffb7b1150f9bba513dcadc1a7f3f86"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "7cc96a1ce231265f5c6554b1936ead0cf448b89e1054dcd60e45ce68d6fc2137"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.2.tar.gz"
[[NCCL]]
arch = "x86_64"
cuda = "12.3"
git-tree-sha1 = "a9019d0299a35d3c99df44438f041122898d3994"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "54eac9bd09194001d9b65bb07c17ddc3f2a58ea0568882580be93909cb4246ad"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.x86_64-linux-gnu-cuda+12.3.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.3"
cuda_platform = "sbsa"
git-tree-sha1 = "120f413608cd711422956f4db217709643b508bb"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "34d8eaddb6908d161cb20812f1a9687dfbf84ea226dd79c81531875ab88bc63a"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.3.tar.gz"
[[NCCL]]
arch = "x86_64"
cuda = "12.4"
git-tree-sha1 = "2f678a978cf6f3a462acffea8042738292956d2c"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "9dbb660889dc6495b24276d363fcbc5401b88199dff59595ce6bebbcba6e3db5"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.x86_64-linux-gnu-cuda+12.4.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.4"
cuda_platform = "jetson"
git-tree-sha1 = "ce1a0db536ad4d3a4db7c1f01508066286d78b9d"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "8f8678ea68ee83f094bff561a01522c07c04ff1865d5abb8a9f8048a1dabcccb"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.4.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.4"
cuda_platform = "sbsa"
git-tree-sha1 = "5b24b6b25a327cc233d66b7e4405fc001d739a2c"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "72bbb8340cdd907d6e24498f14f7674f4936626bf3473f5adfb4b22bac53323f"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.4.tar.gz"
[[NCCL]]
arch = "x86_64"
cuda = "12.5"
git-tree-sha1 = "25ccad8d056670e5b334a01954f932fd04de807f"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "f7a6e799fcf00fe5134c6ec7adc2c99949fe66dee3c3f033bd4a3798c8a651fc"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.x86_64-linux-gnu-cuda+12.5.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.5"
cuda_platform = "jetson"
git-tree-sha1 = "6a606bad95336aa133ee344ace879633bd618fbd"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "73bd862a1fffb5d7d3a0bb3c9130a5726a4e881e21dd02d8e48797ee6f489111"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.5.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.5"
cuda_platform = "sbsa"
git-tree-sha1 = "d838011a4cbcbb2c29b557a2c3736e757ae5a670"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "df2413a6d95b99e15d15d9aed2b3ebaf3b15eece7013fb941058ded263b56ae0"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.5.tar.gz"
[[NCCL]]
arch = "x86_64"
cuda = "12.6"
git-tree-sha1 = "6a74029eeec43390e01d9536eeab37f67a621f0f"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "281149190954a51c11f89e42680253d34e62888c1c1d366c3e731f306e57e247"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.x86_64-linux-gnu-cuda+12.6.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.6"
cuda_platform = "jetson"
git-tree-sha1 = "6fd6fc26e0705e6ad10305b39dbecca2b8a1954b"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "c770fd235e4a83e1103ed00b53123cf093417e7c5b2f5144a24cdfa8c37259f2"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.6.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.6"
cuda_platform = "sbsa"
git-tree-sha1 = "7f430c557860b5d7ae2122c88b963868a960bdb4"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "a934c9f65ae330b9a8baa7fa307b8ddd5e8e4586d891ce2e2f4062e1111ad564"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.6.tar.gz"
[[NCCL]]
arch = "x86_64"
cuda = "12.8"
git-tree-sha1 = "172fcbe97e5dbfa7335446fce1e43c45a40d3837"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "cc59f5a2f4bb1a69f0500ea6b27913234e12acbb2645abf4011d096529d665e9"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.x86_64-linux-gnu-cuda+12.8.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.8"
cuda_platform = "jetson"
git-tree-sha1 = "672089d0e69e6da25dda6da1ac5120883df299e5"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "8d9dda3df5ba597bbc9bd15f9aefbb77bb4e54089a1e906c8bcf69ac7c603319"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.8.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.8"
cuda_platform = "sbsa"
git-tree-sha1 = "8eb1da20b2ad3b957c23c96dfc81ba9f67bfb6b6"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "179ca6c2e0a50a606c6b1c07ebdd3e9605e526ffa6dee422f870e99b0a2fa216"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.8.tar.gz"
[[NCCL]]
arch = "x86_64"
cuda = "12.9"
git-tree-sha1 = "16288aa25540fe286bc528e4cfd45c7abccf23a1"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "65ff4920d333efb63878470886c98edc39f2ebfaf2f57adf060fa68e046fb8ca"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.x86_64-linux-gnu-cuda+12.9.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.9"
cuda_platform = "jetson"
git-tree-sha1 = "bfe01417b990488c6fd0f7e5741f55f39fd25085"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "2dbfee1de304c488a2fb6cb5d12420cfd00bb6b6c1cb3abe0f6cf96374f02570"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.9.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "12.9"
cuda_platform = "sbsa"
git-tree-sha1 = "5c4a5b24b7045da245f2b833be5719e9b59081b7"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "c2f1ae4a3e62376d903a1940b72e01f63e4e2a68ae326fb2db1f726c86703ae1"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.9.tar.gz"
[[NCCL]]
arch = "x86_64"
cuda = "13.0"
git-tree-sha1 = "8fd89e57df0b577f864bd11a467ad975ece1767b"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "d8005723b7eb3b7cc6463bc3268b3f531ce1f95aaf30990017a7f7d7b6bebc43"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.x86_64-linux-gnu-cuda+13.0.tar.gz"
[[NCCL]]
arch = "aarch64"
cuda = "13.0"
git-tree-sha1 = "2afff40a8c944d454f662ad1fa264d3f278bbf97"
libc = "glibc"
os = "linux"

    [[NCCL.download]]
    sha256 = "7c88da76e2845f5d4a0157451b39f59521ee43da9d70a1ff01cc3a06bd98180f"
    url = "https://github.com/JuliaBinaryWrappers/NCCL_jll.jl/releases/download/NCCL-v2.28.9+0/NCCL.v2.28.9.aarch64-linux-gnu-cuda+13.0.tar.gz"
