# Autogenerated wrapper script for NCCL_jll for powerpc64le-linux-gnu-cuda+11.8
export libnccl

using CUDA_Runtime_jll
JLLWrappers.@generate_wrapper_header("NCCL")
JLLWrappers.@declare_library_product(libnccl, "libnccl.so.2")
function __init__()
    JLLWrappers.@generate_init_header(CUDA_Runtime_jll)
    JLLWrappers.@init_library_product(
        libnccl,
        "lib/libnccl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
