# Autogenerated wrapper script for NCCL_jll for x86_64-linux-gnu-cuda+13.0
export libnccl

JLLWrappers.@generate_wrapper_header("NCCL")
JLLWrappers.@declare_library_product(libnccl, "libnccl.so.2")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libnccl,
        "lib/libnccl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
