# Autogenerated wrapper script for NCCL_jll for x86_64-linux-gnu-cuda+10.2
export libnccl

using CUDA_loader_jll
JLLWrappers.@generate_wrapper_header("NCCL")
JLLWrappers.@declare_library_product(libnccl, "libnccl.so.2")
function __init__()
    JLLWrappers.@generate_init_header(CUDA_loader_jll)
    JLLWrappers.@init_library_product(
        libnccl,
        "lib/libnccl.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
